from typed_envs.typing import EnvRegistry

ENVIRONMENT: EnvRegistry = {}
_ENVIRONMENT_VARIABLES_SET_BY_USER: EnvRegistry = {}
_ENVIRONMENT_VARIABLES_USING_DEFAULTS: EnvRegistry = {}

__all__ = [
    "ENVIRONMENT",
    "_ENVIRONMENT_VARIABLES_SET_BY_USER",
    "_ENVIRONMENT_VARIABLES_USING_DEFAULTS",
]